name: Go

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.22", "1.23"]
    name: Lint and test ${{ matrix.go-version == '1.23' && '(latest)' || '(old)' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get install libolm-dev libolm3
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          pip install pre-commit
          export PATH="$HOME/go/bin:$PATH"
          mkdir -p web/dist
          touch web/dist/empty

      - name: Build
        run: go build -v ./...

      - name: Lint
        run: pre-commit run -a

      - name: Test
        run: go test -v ./...
